menu:
    Blog: /
    Archive: /archives/
    CodePen: http://codepen.io/thisis577
    GitHub: https://github.com/thisis577

favicon: /profile.png
logo: /profile.png

# social_icons
# social_icons:
#   enable: true
#   GitHub: github
#   CodePen: codepen

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-81119231-1

# Copyright Infomation
startyear: 2016

