menu:
    Blog: /
    Archive: /archives/
    Codepen: http://codepen.io/thisis577
    GitHub: https://github.com/thisis577

favicon: /profile.png
logo: /profile.png

# Siderbar
# sidbar: right
# widgets:
# - category
# - tag
# - tagCloud

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-81119231-1

# Copyright Infomation
startyear: 2016

# SASS
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false
